main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: pdettori
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: edge-experiments
    username: pdettori
    email: dettori@us.ibm.com
    dev_revision: main

  s3:
    bucket:
      name: kystbucket1
      region: us-west-2
      message:
        aggregation:
          count: 100
      custom:
        endpoint:
          enabled: false
